// <auto-generated />
using System;
using DrugAbuseReportingSystem.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugAbuseReportingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605150316_InsertData")]
    partial class InsertData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrugAbuseReportingSystem.Models.AdminUser", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminId");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "admin@drugabusereporting.com",
                            FullName = "System Administrator",
                            LastLogin = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "admin123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DrugAbuseReportingSystem.Models.DrugInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DrugInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cannabis, also known as marijuana among other names, is a psychoactive drug from the Cannabis plant.",
                            Effects = "Euphoria, relaxation, altered perception of time and space",
                            ImagePath = "/images/drugs/cannabis.jpg",
                            Name = "Cannabis",
                            Risks = "Impaired memory, lung damage (from smoking), potential for addiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cocaine is a powerful stimulant drug made from the leaves of the coca plant native to South America.",
                            Effects = "Increased energy, euphoria, talkativeness, mental alertness",
                            ImagePath = "/images/drugs/cocaine.jpg",
                            Name = "Cocaine",
                            Risks = "Heart attack, stroke, seizures, respiratory failure, addiction"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Heroin is an opioid drug made from morphine, a natural substance taken from the seed pod of the various opium poppy plants grown in Southeast and Southwest Asia, Mexico, and Colombia.",
                            Effects = "People who use heroin report feeling a rush (a surge of pleasure). And then they may feel other effects, such as a warm flushing of the skin, dry mouth, and a heavy feeling in the arms and legs. They may also have severe itching, nausea, and vomiting.",
                            ImagePath = "/images/drugs/heroine.jpg",
                            Name = "Heroin",
                            Risks = "People who use heroin over the long term may develop many different health problems. These problems could include liver, kidney, and lung disease, mental disorders, and abscesses."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Methamphetamines are stimulants, a type of drug that lets people stay awake and do continuous activity with less need for sleep",
                            Effects = "typically include feelings of euphoria and increased alertness and energy. It can also cause serious negative health effects, including paranoia, anxiety, rapid heart rate, irregular heartbeat, stroke, or even death",
                            ImagePath = "/images/drugs/metham.jpg",
                            Name = "Methamphetamine",
                            Risks = "use may lead to insomnia, memory loss, development of a substance use disorder, and other health problems."
                        },
                        new
                        {
                            Id = 6,
                            Description = "MDMA, commonly known as ecstasy or molly, is an empathogen-entactogenic drug with stimulant and minor psychedelic properties. ",
                            Effects = "MDMA’s effects may include feeling more energetic and alert and having an increased sense of well-being, warmth, and openness toward others.",
                            ImagePath = "/images/drugs/MDMA.jpg",
                            Name = "MDMA",
                            Risks = "insomnia, confusion, irritability, anxiety, and depression, impulsiveness and aggression, decreased interest in sex, memory and attention problems, reduced appetite"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Prescription drugs are medications that require a written order from a licensed healthcare professional (like a doctor) to be dispensed by a pharmacist",
                            Effects = "Anxiety, Confusion, Dizziness, Drowsiness, Euphoria, Excessive sleep or inability to sleep, Hyperactivity, Mood swings, Nausea, Unusual muscle movements",
                            ImagePath = "/images/drugs/prescriptionDrugs.jpg",
                            Name = "PrescriptionDrugs",
                            Risks = "Anxiety, Changes in appearance (weight loss or weight gain), Changes in physical health, Damage to the heart, kidneys, liver and brain, Depression, Drug addiction, Drug dependence, Mental health decline"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Synthetic drugs are substances that are created or modified in a laboratory setting, as opposed to being naturally occurring. They can have both therapeutic and psychoactive effects",
                            Effects = "aim to mimic the effects of existing illicit drugs (such as cannabis, cocaine, MDMA and LSD).Euphoria\r\nfeelings of wellbeing\r\nspontaneous laughter and excitement\r\nincreased appetite\r\ndry mouth\r\nquiet and reflective mood",
                            ImagePath = "/images/drugs/SyntheticDrugs.jpg",
                            Name = "SyntheticDrugs",
                            Risks = "rapid heart rate and rapid breathing (tachypnoea)\r\nhypertension (high blood pressure)\r\nheart palpitations\r\nchest pain\r\nvomiting\r\nkidney problems\r\npsychosis\r\nseizures\r\nstroke\r\ndeath."
                        });
                });

            modelBuilder.Entity("DrugAbuseReportingSystem.Models.RehabilitationCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RehabilitationCenters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "555-123-4567",
                            Description = "A comprehensive rehabilitation center offering various treatment programs.",
                            ImagePath = "/images/rehab/hope-center.jpg",
                            Location = "123 Main St, Anytown",
                            Name = "Hope Recovery Center",
                            Services = "Inpatient, Outpatient, Counseling"
                        },
                        new
                        {
                            Id = 2,
                            ContactInfo = "555-987-6543",
                            Description = "Specialized in helping individuals overcome substance abuse.",
                            ImagePath = "/images/rehab/new-beginnings.jpg",
                            Location = "456 Oak Ave, Somewhere",
                            Name = "New Beginnings Clinic",
                            Services = "Detox, Therapy, Aftercare"
                        });
                });

            modelBuilder.Entity("DrugAbuseReportingSystem.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AnonymousContact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DrugType")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
